name: REUSE Compliance

on: [push, pull_request]

jobs:
  reuse:
    runs-on: ubuntu-latest
    name: Check REUSE Compliance
    steps:
    - uses: actions/checkout@v2
    - name: Run REUSE Check
      uses: fsfe/reuse-action@v1
