name: REUSE Compliance

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  reuse:
    runs-on: ubuntu-latest
    name: Check REUSE Compliance
    steps:
      - uses: actions/checkout@v3
      - name: Run REUSE Check
        uses: fsfe/reuse-action@v1
